export const RMV_FROM_SHOPPING_CART = "RMV_FROM_SHOPPING_CART";
export const RMV_TYPE_FROM_SHOPPING_CART = "RMV_TYPE_FROM_SHOPPING_CART";
export const ADD_TO_SHOPPING_CART = "ADD_TO_SHOPPING_CART";
export const CLEAR_SHOPPING_CART = "CLEAR_SHOPPING_CART";



export const RMV_TYPE_FROM_FAVORITE_CART = "RMV_TYPE_FROM_FAVORITE_CART";
export const RMV_FROM_FAVORITE_CART = "RMV_FROM_FAVORITE_CART";
export const ADD_TO_FAVORITE_CART = "ADD_TO_FAVORITE_CART";
export const CLEAR_FAVORITE_CART = "CLEAR_FAVORITE_CART";

export const CURRENT_BEER = "CURRENT_BEER";

export const FETCH_BEGIN_OFFER = "FETCH_BEGIN_OFFER";
export const FETCH_SUCCESS_OFFER = "FETCH_SUCCESS_OFFER";
export const FETCH_FAIL_OFFER = "FETCH_FAIL_OFFER";

export const FETCH_BEGIN_FILTERS = "FETCH_BEGIN_FILTERS";
export const FETCH_SUCCESS_FILTERS = "FETCH_SUCCESS_FILTERS";
export const FETCH_FAIL_FILTERS = "FETCH_FAIL_FILTERS";

export const INCR_ORDER = "INCR_ORDER";
export const DECR_ORDER = "DECR_ORDER";

export const VALID = "VALID";
export const NOT_VALID = "NOT_VALID";


/*
export const RMV_FROM_CART = "RMV_FROM_CART";
export const RMV_TYPE_FROM_CART = "RMV_TYPE_FROM_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";


export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const RMV_TYPE_FROM_FAVORITE = "RMV_TYPE_FROM_FAVORITE";
export const RMV_FROM_FAVORITE = "RMV_FROM_FAVORITE";

export const CLEAR_FAVORITE = "CLEAR_FAVORITE";
export const CURRENT_BEER = "CURRENT_BEER";
export const FETCH_BEGIN = "FETCH_BEGIN";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";
export const FILTERS_FETCH_BEGIN = "FILTERS_FETCH_BEGIN";
export const FILTERS_FETCH_SUCCESS = "FILTERS_FETCH_SUCCESS";
export const FILTERS_FETCH_FAIL = "FILTERS_FETCH_FAIL";
export const INCR_ORDER = "INCR_ORDER";
export const DECR_ORDER = "DECR_ORDER";
export const VALID = "VALID";
export const NOT_VALID = "NOT_VALID";


*/

